import '../models/stock.dart';

class SampleData {
  SampleData._();

  static List<Stock> get watchlistStocks => [
    const Stock(
      id: 'RELIANCE',
      symbol: 'RELIANCE',
      companyName: 'Reliance Industries Ltd.',
      price: 2947.55,
      change: 42.30,
      changePercent: 1.46,
      exchange: 'NSE',
      volume: 12.4,
    ),
    const Stock(
      id: 'TCS',
      symbol: 'TCS',
      companyName: 'Tata Consultancy Services',
      price: 3812.10,
      change: -28.75,
      changePercent: -0.75,
      exchange: 'NSE',
      volume: 4.2,
    ),
    const Stock(
      id: 'HDFCBANK',
      symbol: 'HDFCBANK',
      companyName: 'HDFC Bank Ltd.',
      price: 1623.40,
      change: 18.90,
      changePercent: 1.18,
      exchange: 'NSE',
      volume: 9.8,
    ),
    const Stock(
      id: 'INFY',
      symbol: 'INFY',
      companyName: 'Infosys Ltd.',
      price: 1482.65,
      change: -11.20,
      changePercent: -0.75,
      exchange: 'NSE',
      volume: 6.1,
    ),
    const Stock(
      id: 'ICICIBANK',
      symbol: 'ICICIBANK',
      companyName: 'ICICI Bank Ltd.',
      price: 1108.75,
      change: 23.45,
      changePercent: 2.16,
      exchange: 'NSE',
      volume: 11.3,
    ),
    const Stock(
      id: 'HINDUNILVR',
      symbol: 'HINDUNILVR',
      companyName: 'Hindustan Unilever Ltd.',
      price: 2235.80,
      change: 0.00,
      changePercent: 0.00,
      exchange: 'NSE',
      volume: 2.7,
    ),
    const Stock(
      id: 'SBIN',
      symbol: 'SBIN',
      companyName: 'State Bank of India',
      price: 792.30,
      change: 14.60,
      changePercent: 1.88,
      exchange: 'NSE',
      volume: 18.9,
    ),
    const Stock(
      id: 'BHARTIARTL',
      symbol: 'BHARTIARTL',
      companyName: 'Bharti Airtel Ltd.',
      price: 1587.45,
      change: -32.10,
      changePercent: -1.98,
      exchange: 'NSE',
      volume: 5.6,
    ),
    const Stock(
      id: 'WIPRO',
      symbol: 'WIPRO',
      companyName: 'Wipro Ltd.',
      price: 478.90,
      change: 5.35,
      changePercent: 1.13,
      exchange: 'NSE',
      volume: 7.2,
    ),
    const Stock(
      id: 'MARUTI',
      symbol: 'MARUTI',
      companyName: 'Maruti Suzuki India Ltd.',
      price: 11842.20,
      change: -156.80,
      changePercent: -1.31,
      exchange: 'NSE',
      volume: 1.1,
    ),
  ];
}
